### ISSUE TITLE
 Love this idea

### ISSUE THREAD

**Issue by panoply** [erikvullings/kvk-query#1]
Hey Erik, this would come in very handy. Would be happy to contribute.

**Comment by erikvullings** [comment]
@panoply Hi, I've created a first version - please give it a go, and hopefully it does what you want it to do too. 

I've used it to lookup 2.5k KVK numbers, and got back 14k results (including all branches) as JSON and CSV, and don't expect many changes at the moment...

**Comment by panoply** [comment]
Utterly fantastic. Will be a great help for a friend of mine who was looking for this solution. Many thanks for this and all the work you open source (especially Mithril stuff.

**Comment by erikvullings** [comment]
You're welcome. I'm happy to receive pull requests from you if your friend
needs something else.
